context:
  name: copyparty
  version: "1.19.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 40211fcea9e932dee2c173b74121902d54243712579aa6cd2c6b3230b662ed97

build:
  script: python -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - jinja2

tests:
  - python:
      imports:
        - copyparty
        - copyparty.bos
        - copyparty.res
        - copyparty.stolen
        - copyparty.stolen.dnslib
        - copyparty.stolen.ifaddr
        - copyparty.web
        - copyparty.web.a
        - copyparty.web.deps
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/9001/copyparty
  summary: Portable file server with accelerated resumable uploads, dedup, WebDAV, FTP, TFTP, zeroconf, media indexer, thumbnails++ all in one file, no deps
  description: |
    turn almost any device into a file server with resumable uploads/downloads using any web browser
  license: MIT
  license_file: LICENSE
  documentation: https://github.com/9001/copyparty
  repository: https://github.com/9001/copyparty

extra:
  recipe-maintainers:
    - pavelzw
